language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1

before_install:
  - ./bin/install-wp-test-platform wordpress_test root '' 127.0.0.1 $WP_VERSION

install:
  - composer install
